// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBarDuXGxjHqSnt7CKAMoel1A82srKFRLM',
    appId: '1:874687571084:web:464229bd47f0dc34b987a9',
    messagingSenderId: '874687571084',
    projectId: 'we-chat-f28bc',
    authDomain: 'we-chat-f28bc.firebaseapp.com',
    storageBucket: 'we-chat-f28bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LC6JkNDgJ0lcTz7ZVEyd812JylCa2cg',
    appId: '1:874687571084:android:336d53d8efbfa854b987a9',
    messagingSenderId: '874687571084',
    projectId: 'we-chat-f28bc',
    storageBucket: 'we-chat-f28bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgUNuC4ihcUbp0uYGf07ldKVTMIy84lp4',
    appId: '1:874687571084:ios:a5914a4b73438afdb987a9',
    messagingSenderId: '874687571084',
    projectId: 'we-chat-f28bc',
    storageBucket: 'we-chat-f28bc.appspot.com',
    androidClientId: '874687571084-qc14vkpp279k4shk71d1k2s2d4jkmue2.apps.googleusercontent.com',
    iosClientId: '874687571084-62f69mupmu6jb86g57knkog5pok15nlt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
